Refractoring Selection and Copying Restorer (Universal)
cyfung1031/userscript-supports pull request #10
Opened 2023-06-25 19:52 UTC by SashaXser

This code is too much overloaded, I hope my changes helped the code become better

2023-06-25 23:51 UTC, cyfung1031 commented on a-universal-script-to-re-enable-the-selection-and-copying.user.js
> +const SCRIPT_TAG = "Selection and Copying Restorer (Universal)";
Never put variable outside the first function block

2023-06-25 23:52 UTC, cyfung1031 commented on a-universal-script-to-re-enable-the-selection-and-copying.user.js
> +    const { Promise } = window; // YouTube hacks Promise in WaterFox Classic and "Promise.resolve(0)" nevers resolve.
Avoid all `{ xxxx } = object` if possible. This is only for some special cases like `{ Promise, fetch } = window`

2023-06-25 23:54 UTC, cyfung1031 commented on a-universal-script-to-re-enable-the-selection-and-copying.user.js
> +                    if (typeof selfFunc !== 'function' || selfFunc[$.ksFuncReplacerCounter] !== id) return false;
Please keep original which separates into two lines. Just avoid the if condition getting too long.

2023-06-25 23:55 UTC, cyfung1031 commented on a-universal-script-to-re-enable-the-selection-and-copying.user.js
> +                        if ($.isGlobalEventCheckForFuncReplacer === true && window.event !== ev) return false; // eslint-disable-line
I prefer to keep $.isGlobalEventCheckForFuncReplacer === true separately. It helps the script maintainable.

2023-06-25 23:55 UTC, cyfung1031 commented on a-universal-script-to-re-enable-the-selection-and-copying.user.js
> +                            const { stack } = (new Error());
Same reason as line 104

2023-06-25 23:59 UTC, cyfung1031 commented on a-universal-script-to-re-enable-the-selection-and-copying.user.js
> +            if (!plainText || (evt.cancelable === false || evt.defaultPrevented === true)) return;
Please split into lines as per the original, with comment. For future maintenance. 
It would be easier to insert other if conditions or add debug in between.

2023-06-26 00:01 UTC, cyfung1031 commented on a-universal-script-to-re-enable-the-selection-and-copying.user.js
> +            const { target } = evt;
Avoid all `{ xxxx } = object` if possible. This is only for some special cases like `{ Promise, fetch } = window`

2023-06-26 00:01 UTC, cyfung1031 commented on a-universal-script-to-re-enable-the-selection-and-copying.user.js
> +                    if (!('clipboardData' in evt && 'setData' in DataTransfer.prototype) || (evt.cancelable === false || evt.defaultPrevented === true)) return true; // Event oncopy not supporting cl
Please keep original which separates into two lines. Just avoid the if condition getting too long.

Please split into lines as per the original, with comment. For future maintenance.
It would be easier to insert other if conditions or add debug in between.

2023-06-26 00:05 UTC, cyfung1031 commented on a-universal-script-to-re-enable-the-selection-and-copying.user.js
> +            if (targetElm instanceof Element && targetElm.matches('*:hover') && (getComputedStyle(targetElm).getPropertyValue('cursor') === 'pointer' && targetElm.textContent)) return true;
Please keep original which separates into two lines. Just avoid the if condition getting too long.

Please split into lines as per the original, with comment. For future maintenance.
It would be easier to insert other if conditions or add debug in between.

first line `targetElm instanceof Element && targetElm.matches('*:hover')` refers to non-reflow/repaint checking
second line `getComputedStyle(targetElm).getPropertyValue('cursor') === 'pointer' && targetElm.textContent` refers to the DOM operation in the page that creating reflow/repaint which affect the performance of execution.

2023-06-26 00:06 UTC, SashaXser commented
Why didn't you feel comfortable? Maybe it's just the way you're used to writing code

2023-06-26 00:06 UTC, cyfung1031 commented on a-universal-script-to-re-enable-the-selection-and-copying.user.js
> +for (const video of document.querySelectorAll('video[src]')) {
1. leading spaces are missing?
2. Please add the `// prevent poor video performance` back.

2023-06-26 00:07 UTC, SashaXser commented on a-universal-script-to-re-enable-the-selection-and-copying.user.js
> +for (const video of document.querySelectorAll('video[src]')) {
I just don't understand some of your logic, why are your suggestions better than mine?

2023-06-26 00:42 UTC, cyfung1031 requested changes
## Overall
I noted some good changes from your suggestions.
However, there are changes have to be made before merging.
In short,
1. some comments should not be removed.
2.`{ xxx } = yyy` shall be avoided.
3. do not change if block to if return. The execution could be the same but there is a logically difference.
4. do not merge the if conditions. There is no performance gain. It just make the script difficult to read and maintain.
5. Some mistakes made in your update (e.g. leading spaces, "half-way refactoring")

## Remarks

### Intended Redundancy and `const`/`let`
Some coding writing is intended to be redundant to allow easy debug or editing.
but recently i accepted that people using `const` instead of `let` in the coding. using `let` can let developers to change the code easier, but it seems that `const` is necessary as some coding checker will treat it as the only correct way for coding. I am not 100% agree this school of thought. JS is flexible.

### regarding `if ( condition ) {} else {}`
It is my personal preference to code like this in JavaScript. Some comparators (e.g. >) has no exactly the same counter-comparator. `a > 0` is `false` is not necessary `a <=0` is true. (e.g. `NaN`)
Anyway, I don't mind them being changed to `if ( !(condition) ) {}`


-----------

Please update accordingly.

2023-06-26 00:42 UTC, cyfung1031 commented on a-universal-script-to-re-enable-the-selection-and-copying.user.js
> +                                    const { parentNode } = pElm
Avoid all `{ xxxx } = object` if possible. This is only for some special cases like `{ Promise, fetch } = window`
This sugar syntax will also make difficulties in future that developers who want to change the variable name for debug or other reasons.

2023-06-26 00:42 UTC, cyfung1031 commented on a-universal-script-to-re-enable-the-selection-and-copying.user.js
> +            if ($.lpKeyPressing === true) {
Why you changed `else if` to `if`? It is logically different and it makes the javascript engine to check this condition even if the first condition has been fulfilled.

2023-06-26 00:42 UTC, cyfung1031 commented on a-universal-script-to-re-enable-the-selection-and-copying.user.js
> +                return;
avoid `return` if possible.
`return` is convenient but it reduces the code readability. For example we have hundreds of lines in a single coding block, and we would have difficulty to alert there is a line with `return` in between. It would increase the difficulty for debuging.

usually I would just put `if(!xxx) return;` in the beginning of code block so that 
1. it is known as general condition to not execute the code block.
2. it is trivial because it is short.
3. avoid too many indents due to nested scope. 


When you use 
```js
if (a || b || c){
   funcA();
   funcB();
   ...
}
```
we can easily understand those conditions are the necessity to run the `funcA` `funcB`


while `if (!$.gm_lp_enable) return;` means that we do not run the following code if the script is not enable.

2023-06-26 00:42 UTC, cyfung1031 commented on a-universal-script-to-re-enable-the-selection-and-copying.user.js
> +                return;
avoid `return` if possible as mentioned above.

```js
if (a ===1) {
   a=2;
   doSomething();
}
````

is a common coding pattern for state variable.

we can add more logics easily afterwards.

```js
if (a ===1) {
   a=2;
   doSomething();
}
if (a ===7) {
   a=8;
   doSomethingElse();
}
````

2023-06-26 00:42 UTC, cyfung1031 commented on a-universal-script-to-re-enable-the-selection-and-copying.user.js
> +                if (!(targetElm instanceof Element) || "|SVG|IMG|HTML|BODY|VIDEO|AUDIO|BR|HEAD|NOSCRIPT|SCRIPT|STYLE|TEXTAREA|AREA|INPUT|FORM|BUTTON|".indexOf(`|${targetElm.nodeName}|`) >= 0) return;
Please keep original which separates into two lines. Just avoid the if condition getting too long.

Please split into lines as per the original, with comment. For future maintenance.
It would be easier to insert other if conditions or add debug in between.

2023-06-26 00:42 UTC, cyfung1031 commented on a-universal-script-to-re-enable-the-selection-and-copying.user.js
> +                    return;
avoid `return` if possible as mentioned above

2023-06-26 00:42 UTC, cyfung1031 commented on a-universal-script-to-re-enable-the-selection-and-copying.user.js
> +                return;
avoid `return` if possible as mentioned above

2023-06-26 00:42 UTC, cyfung1031 commented on a-universal-script-to-re-enable-the-selection-and-copying.user.js
> +                return;
avoid `return` if possible as mentioned above

2023-06-26 00:42 UTC, cyfung1031 commented on a-universal-script-to-re-enable-the-selection-and-copying.user.js
> +            if (evt.button === 1 && evt.timeStamp - $.dmmMouseUpCancel < 40) {
Please keep original which separates into two lines. Just avoid the if condition getting too long.

Please split into lines as per the original, with comment. For future maintenance.
It would be easier to insert other if conditions or add debug in between.

2023-06-26 00:42 UTC, cyfung1031 commented on a-universal-script-to-re-enable-the-selection-and-copying.user.js
> +                    }
If you want to make the coding better, why you just change `a?b:c` ?

2023-06-26 00:42 UTC, cyfung1031 commented on a-universal-script-to-re-enable-the-selection-and-copying.user.js
> +            if (evtType === 'contextmenu' && evt.defaultPrevented !== true) {
Please keep original which separates into two lines. Just avoid the if condition getting too long.

Please split into lines as per the original, with comment. For future maintenance.
It would be easier to insert other if conditions or add debug in between.

2023-06-26 00:42 UTC, cyfung1031 commented on a-universal-script-to-re-enable-the-selection-and-copying.user.js
> +                return;
avoid `return` if possible as mentioned above.

2023-06-26 00:42 UTC, cyfung1031 commented on a-universal-script-to-re-enable-the-selection-and-copying.user.js
> +                return;
avoid `return` if possible as mentioned above.

2023-06-26 00:42 UTC, cyfung1031 commented on a-universal-script-to-re-enable-the-selection-and-copying.user.js
> +        return;
avoid `return` if possible as mentioned above.

2023-06-26 01:30 UTC, SashaXser commented
I tried to please you, check the edits

2023-06-28 07:20 UTC, closed without merging